project is ready for a code review
misterSokor/litflix pull request #3
Opened 2024-08-31 02:52 UTC by misterSokor

2024-09-01 09:45 UTC, Elena-Bruyako requested changes
see comment

2024-09-01 09:45 UTC, Elena-Bruyako commented on src/main/java/com/store/litflix/controller/BookController.java
> +    Optional<Book> getBook(@PathVariable Long id) {
```suggestion
    BookDto getBook(@PathVariable Long id) {
```

2024-09-01 09:45 UTC, Elena-Bruyako commented on src/main/java/com/store/litflix/controller/BookController.java
>      List<Book> getAllBooks() {
```suggestion
    List<BookDto> getAllBooks() {
```

2024-09-01 09:45 UTC, Elena-Bruyako commented on src/main/java/com/store/litflix/repository/BookRepository.java
> +//    Book save(Book book);
remove comments

2024-09-01 09:45 UTC, Elena-Bruyako commented on src/main/java/com/store/litflix/service/impl/BookServiceImpl.java
> +    public Optional<Book> findById(Long id) {
```suggestion
    public BookDto findById(Long id) {
```

2024-09-01 09:45 UTC, Elena-Bruyako commented on src/main/java/com/store/litflix/service/impl/BookServiceImpl.java
> +        }
```suggestion
        Book book = bookRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException("Book not found with id " + id);
        bookMapper.updateBookFromDto(bookDto, book);
        bookRepository.save(book);
        return bookMapper.toDto(book);
```

2024-09-01 09:45 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/02-add-isDeleted-to-books-table.yaml
> +              - column:
replace to existing changelog 01

2024-09-02 21:55 UTC, misterSokor commented on src/main/resources/db/changelog/changes/02-add-isDeleted-to-books-table.yaml
> +              - column:
Could you please clarify? I have to delete  01-create-books-table.yaml file and to replace it with 02-add-isDeleted-to-books-table.yaml?

2024-09-03 07:31 UTC, Elena-Bruyako requested changes
see comments

2024-09-03 07:31 UTC, Elena-Bruyako commented on src/main/java/com/store/litflix/controller/BookController.java
> +    Optional<Book> getBook(@PathVariable Long id) {
not fixed

2024-09-03 07:31 UTC, Elena-Bruyako commented on src/main/java/com/store/litflix/controller/BookController.java
> +    void deleteById(@PathVariable Long id) {
make all endpoints public

2024-09-03 07:31 UTC, Elena-Bruyako commented on src/main/java/com/store/litflix/service/impl/BookServiceImpl.java
>          Book savedBook = bookRepository.save(book);
```suggestion
        bookRepository.save(book);
```

2024-09-03 07:31 UTC, Elena-Bruyako commented on src/main/java/com/store/litflix/service/impl/BookServiceImpl.java
> +        return bookMapper.toDto(savedBook);
```suggestion
        return bookMapper.toDto(book);
```

2024-09-03 07:31 UTC, Elena-Bruyako commented on src/main/java/com/store/litflix/service/impl/BookServiceImpl.java
> +    public Optional<Book> findById(Long id) {
not fixed

2024-09-03 07:31 UTC, Elena-Bruyako commented on src/main/java/com/store/litflix/service/impl/BookServiceImpl.java
> +        }
```suggestion
        Book book = bookRepository.findById(id)
                    .orElseThrow(() -> new EntityNotFoundException("Book not "
                                                                   + "found with id " + id));
        bookMapper.updateModelFromDto(requestDto, book);
        bookRepository.save(book);
        return bookMapper.toDto(book);
```

2024-09-03 07:31 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/02-add-isDeleted-to-books-table.yaml
> +              - column:
Add column is_deleted to existing 01 changelog
If you have questions please ask in chat

2024-09-04 14:25 UTC, misterSokor commented on src/main/java/com/store/litflix/controller/BookController.java
>      List<Book> getAllBooks() {
the same thing here

2024-09-04 14:33 UTC, misterSokor commented on src/main/resources/db/changelog/changes/02-add-isDeleted-to-books-table.yaml
> +              - column:
Thanks

2024-09-05 11:13 UTC, Elena-Bruyako requested changes
see comment

2024-09-05 11:13 UTC, Elena-Bruyako commented on src/main/java/com/store/litflix/service/impl/BookServiceImpl.java
> +    public Optional<Book> findById(Long id) {
findById method should return BookDto on Service layer
i've never suggested to return Optional<Book> from this method in any commits.

2024-09-06 10:25 UTC, Elena-Bruyako approved these changes

2024-09-08 02:26 UTC, merged